source "https://rubygems.org"
ruby "2.2.2"

gem "compass"
gem "breakpoint"
gem "foreman"
gem "dotenv"
gem "middleman"
gem "middleman-autoprefixer"
gem "middleman-deploy"
gem "middleman-livereload"
gem "sass"
gem "slim"
gem "susy"
gem "pry"
