source "https://rubygems.org"
ruby "2.1.5"

gem "compass"
gem "breakpoint"
gem "exo", git: "https://c0ec41c6da86a92466a61d5e3d4999a9fc2339f8:x-oauth-basic@github.com/metalabdesign/exo.git"
gem "middleman"
gem "foreman"
gem "middleman-autoprefixer"
gem "middleman-deploy"
gem "middleman-livereload"
gem "middleman-favicon-maker"
gem "sass"
gem "slim"
gem "susy"
